image: python:3.7.9-slim

before_script:
    - pip install flake8

stages:
    - Static Analysis

flake8:
  stage: Static Analysis
  script:
    - flake8 --max-line-length=120 --count /builds/CAPTAIN_EU6117_2017/interactive-clustering/
